import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "src/core/cognitive-v021/**/*.test.ts",
      "src/core/cognition/continuity-diagnostics.test.ts",
      "src/core/cognition/migration-23.test.ts",
      "src/core/cognition/migration-24.test.ts",
      "src/core/cognition/migration-25.test.ts",
      "src/core/cognition/migration-44.test.ts",
      "src/core/cognition/open-items.test.ts",
      "src/core/cognition/reconsideration.test.ts",
      "src/core/cognition/schema-content-recovery.test.ts",
      "src/core/cognition/wake-selection.test.ts",
      "src/core/attention/**/*.test.ts",
      "src/core/cognitive-graduation/**/*.test.ts",
      "src/core/context-allocation/**/*.test.ts",
      "src/core/delivery/**/*.test.ts",
      "src/core/identity/**/*.test.ts",
      "src/core/learned-autonomy/**/*.test.ts",
      "src/core/memory/**/*.test.ts",
      "src/core/model-fabric/**/*.test.ts",
      "src/core/model-routing/**/*.test.ts",
      "src/core/privacy/**/*.test.ts",
      "src/core/perception/**/*.test.ts",
      "src/core/reflection/**/*.test.ts",
      "src/core/relationship/**/*.test.ts",
      "src/core/rollout/**/*.test.ts",
      "src/core/state/**/*.test.ts",
      "src/capabilities-endpoint.test.ts",
      "src/data-plane-authority.test.ts",
      "src/dispatch-data-plane.test.ts",
      "src/env.test.ts",
      "src/health.test.ts",
      "src/initiative-status-auth.test.ts",
      "src/owner-auth.test.ts",
      "src/route-surface.test.ts",
      "src/serve-inbox-consumer.test.ts",
      "src/mistral-client.test.ts",
      "src/typography.test.ts",
    ],
    exclude: [...configDefaults.exclude],
    environment: "node",
    testTimeout: 20_000,
  },
});
